### ISSUE TITLE
Sort Torch Fire Starters

### ISSUE THREAD

**Issue by SenorSmartyPants** [Remodor/TLD_FireImprovements#5]
I'd like to use my worst ignite chance matches/firestriker to light a torch (since that never fails). Here is my current inventory.

![image](https://user-images.githubusercontent.com/991618/146979192-8f829314-ce6a-4ddb-9c92-570dbaaeca5e.png)

I set worst firestrike and worst matches to true
![image](https://user-images.githubusercontent.com/991618/146979676-16179394-f6e2-4bd2-ac8f-471fa2d75ecb.png)
But it comes up with wood matches first, then cardboard, then striker. It doesn't matter if I change those settings to false.
![image](https://user-images.githubusercontent.com/991618/146979738-180398e6-f5d4-464b-aa5c-0d861ff80a3a.png)

Condition on matches doesn't affect ignite chance as far as I am aware.

**Comment by Remodor** [comment]
Maybe the description is not explicit enough. __Worst__ means in this case __worst__ condition, not worst chance.. 
(Will get changed, thx for the hint!)
Thought about modifying the list, but the necessary function is sadly not patchable (inlined for optimization).

But... Found a workaround though ;)
With the next release, there will be another option to sort the torch starters.
